//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BA.Admin.Web.ProductWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductDto", Namespace="http://www.orderbyapps.com/WebServices/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<BA.Admin.Web.ProductWebService.ProductDto>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BA.Admin.Web.ProductWebService.BaseDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<BA.Admin.Web.ProductWebService.SupplierDto>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BA.Admin.Web.ProductWebService.SupplierDto))]
    public partial class ProductDto : BA.Admin.Web.ProductWebService.BaseDto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object SupplierIdField;
        
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] SketchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object SellingPeriodIdField;
        
        private bool DisabledField;
        
        private decimal DiscountAmountField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public object CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryIdField, value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public object SupplierId {
            get {
                return this.SupplierIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierIdField, value) != true)) {
                    this.SupplierIdField = value;
                    this.RaisePropertyChanged("SupplierId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public byte[] Sketch {
            get {
                return this.SketchField;
            }
            set {
                if ((object.ReferenceEquals(this.SketchField, value) != true)) {
                    this.SketchField = value;
                    this.RaisePropertyChanged("Sketch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public object SellingPeriodId {
            get {
                return this.SellingPeriodIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SellingPeriodIdField, value) != true)) {
                    this.SellingPeriodIdField = value;
                    this.RaisePropertyChanged("SellingPeriodId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public bool Disabled {
            get {
                return this.DisabledField;
            }
            set {
                if ((this.DisabledField.Equals(value) != true)) {
                    this.DisabledField = value;
                    this.RaisePropertyChanged("Disabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public decimal DiscountAmount {
            get {
                return this.DiscountAmountField;
            }
            set {
                if ((this.DiscountAmountField.Equals(value) != true)) {
                    this.DiscountAmountField = value;
                    this.RaisePropertyChanged("DiscountAmount");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseDto", Namespace="http://www.orderbyapps.com/WebServices/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BA.Admin.Web.ProductWebService.SupplierDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BA.Admin.Web.ProductWebService.ProductDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<BA.Admin.Web.ProductWebService.ProductDto>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.List<BA.Admin.Web.ProductWebService.SupplierDto>))]
    public partial class BaseDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StringId {
            get {
                return this.StringIdField;
            }
            set {
                if ((object.ReferenceEquals(this.StringIdField, value) != true)) {
                    this.StringIdField = value;
                    this.RaisePropertyChanged("StringId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Display {
            get {
                return this.DisplayField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayField, value) != true)) {
                    this.DisplayField = value;
                    this.RaisePropertyChanged("Display");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SupplierDto", Namespace="http://www.orderbyapps.com/WebServices/")]
    [System.SerializableAttribute()]
    public partial class SupplierDto : BA.Admin.Web.ProductWebService.BaseDto {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactPersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactFaxField;
        
        private int CategoryIdField;
        
        private int NationIdField;
        
        private bool AllowTakeOutField;
        
        private bool AllowReserveField;
        
        private bool AllowBringWineField;
        
        private System.Nullable<System.DateTime> DayStartTimeField;
        
        private System.Nullable<System.DateTime> DayEndTimeField;
        
        private decimal RatingField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AddressLine1 {
            get {
                return this.AddressLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine1Field, value) != true)) {
                    this.AddressLine1Field = value;
                    this.RaisePropertyChanged("AddressLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AddressLine2 {
            get {
                return this.AddressLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine2Field, value) != true)) {
                    this.AddressLine2Field = value;
                    this.RaisePropertyChanged("AddressLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CountryState {
            get {
                return this.CountryStateField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryStateField, value) != true)) {
                    this.CountryStateField = value;
                    this.RaisePropertyChanged("CountryState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ContactPerson {
            get {
                return this.ContactPersonField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactPersonField, value) != true)) {
                    this.ContactPersonField = value;
                    this.RaisePropertyChanged("ContactPerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ContactPhone {
            get {
                return this.ContactPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactPhoneField, value) != true)) {
                    this.ContactPhoneField = value;
                    this.RaisePropertyChanged("ContactPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string ContactEmail {
            get {
                return this.ContactEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactEmailField, value) != true)) {
                    this.ContactEmailField = value;
                    this.RaisePropertyChanged("ContactEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string ContactFax {
            get {
                return this.ContactFaxField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactFaxField, value) != true)) {
                    this.ContactFaxField = value;
                    this.RaisePropertyChanged("ContactFax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public int NationId {
            get {
                return this.NationIdField;
            }
            set {
                if ((this.NationIdField.Equals(value) != true)) {
                    this.NationIdField = value;
                    this.RaisePropertyChanged("NationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public bool AllowTakeOut {
            get {
                return this.AllowTakeOutField;
            }
            set {
                if ((this.AllowTakeOutField.Equals(value) != true)) {
                    this.AllowTakeOutField = value;
                    this.RaisePropertyChanged("AllowTakeOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public bool AllowReserve {
            get {
                return this.AllowReserveField;
            }
            set {
                if ((this.AllowReserveField.Equals(value) != true)) {
                    this.AllowReserveField = value;
                    this.RaisePropertyChanged("AllowReserve");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public bool AllowBringWine {
            get {
                return this.AllowBringWineField;
            }
            set {
                if ((this.AllowBringWineField.Equals(value) != true)) {
                    this.AllowBringWineField = value;
                    this.RaisePropertyChanged("AllowBringWine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public System.Nullable<System.DateTime> DayStartTime {
            get {
                return this.DayStartTimeField;
            }
            set {
                if ((this.DayStartTimeField.Equals(value) != true)) {
                    this.DayStartTimeField = value;
                    this.RaisePropertyChanged("DayStartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public System.Nullable<System.DateTime> DayEndTime {
            get {
                return this.DayEndTimeField;
            }
            set {
                if ((this.DayEndTimeField.Equals(value) != true)) {
                    this.DayEndTimeField = value;
                    this.RaisePropertyChanged("DayEndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public decimal Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((this.RatingField.Equals(value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.orderbyapps.com/WebServices/", ConfigurationName="ProductWebService.ProductWebServiceSoap")]
    public interface ProductWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name RetrieveProductsBySupplierResult from namespace http://www.orderbyapps.com/WebServices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.orderbyapps.com/WebServices/RetrieveProductsBySupplier", ReplyAction="*")]
        BA.Admin.Web.ProductWebService.RetrieveProductsBySupplierResponse RetrieveProductsBySupplier(BA.Admin.Web.ProductWebService.RetrieveProductsBySupplierRequest request);
        
        // CODEGEN: Generating message contract since element name RetrieveAllSupplierResult from namespace http://www.orderbyapps.com/WebServices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.orderbyapps.com/WebServices/RetrieveAllSupplier", ReplyAction="*")]
        BA.Admin.Web.ProductWebService.RetrieveAllSupplierResponse RetrieveAllSupplier(BA.Admin.Web.ProductWebService.RetrieveAllSupplierRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveProductsBySupplierRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveProductsBySupplier", Namespace="http://www.orderbyapps.com/WebServices/", Order=0)]
        public BA.Admin.Web.ProductWebService.RetrieveProductsBySupplierRequestBody Body;
        
        public RetrieveProductsBySupplierRequest() {
        }
        
        public RetrieveProductsBySupplierRequest(BA.Admin.Web.ProductWebService.RetrieveProductsBySupplierRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.orderbyapps.com/WebServices/")]
    public partial class RetrieveProductsBySupplierRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int supplierId;
        
        public RetrieveProductsBySupplierRequestBody() {
        }
        
        public RetrieveProductsBySupplierRequestBody(int supplierId) {
            this.supplierId = supplierId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveProductsBySupplierResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveProductsBySupplierResponse", Namespace="http://www.orderbyapps.com/WebServices/", Order=0)]
        public BA.Admin.Web.ProductWebService.RetrieveProductsBySupplierResponseBody Body;
        
        public RetrieveProductsBySupplierResponse() {
        }
        
        public RetrieveProductsBySupplierResponse(BA.Admin.Web.ProductWebService.RetrieveProductsBySupplierResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.orderbyapps.com/WebServices/")]
    public partial class RetrieveProductsBySupplierResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<BA.Admin.Web.ProductWebService.ProductDto> RetrieveProductsBySupplierResult;
        
        public RetrieveProductsBySupplierResponseBody() {
        }
        
        public RetrieveProductsBySupplierResponseBody(System.Collections.Generic.List<BA.Admin.Web.ProductWebService.ProductDto> RetrieveProductsBySupplierResult) {
            this.RetrieveProductsBySupplierResult = RetrieveProductsBySupplierResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveAllSupplierRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveAllSupplier", Namespace="http://www.orderbyapps.com/WebServices/", Order=0)]
        public BA.Admin.Web.ProductWebService.RetrieveAllSupplierRequestBody Body;
        
        public RetrieveAllSupplierRequest() {
        }
        
        public RetrieveAllSupplierRequest(BA.Admin.Web.ProductWebService.RetrieveAllSupplierRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RetrieveAllSupplierRequestBody {
        
        public RetrieveAllSupplierRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveAllSupplierResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveAllSupplierResponse", Namespace="http://www.orderbyapps.com/WebServices/", Order=0)]
        public BA.Admin.Web.ProductWebService.RetrieveAllSupplierResponseBody Body;
        
        public RetrieveAllSupplierResponse() {
        }
        
        public RetrieveAllSupplierResponse(BA.Admin.Web.ProductWebService.RetrieveAllSupplierResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.orderbyapps.com/WebServices/")]
    public partial class RetrieveAllSupplierResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<BA.Admin.Web.ProductWebService.SupplierDto> RetrieveAllSupplierResult;
        
        public RetrieveAllSupplierResponseBody() {
        }
        
        public RetrieveAllSupplierResponseBody(System.Collections.Generic.List<BA.Admin.Web.ProductWebService.SupplierDto> RetrieveAllSupplierResult) {
            this.RetrieveAllSupplierResult = RetrieveAllSupplierResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductWebServiceSoapChannel : BA.Admin.Web.ProductWebService.ProductWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductWebServiceSoapClient : System.ServiceModel.ClientBase<BA.Admin.Web.ProductWebService.ProductWebServiceSoap>, BA.Admin.Web.ProductWebService.ProductWebServiceSoap {
        
        public ProductWebServiceSoapClient() {
        }
        
        public ProductWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BA.Admin.Web.ProductWebService.RetrieveProductsBySupplierResponse BA.Admin.Web.ProductWebService.ProductWebServiceSoap.RetrieveProductsBySupplier(BA.Admin.Web.ProductWebService.RetrieveProductsBySupplierRequest request) {
            return base.Channel.RetrieveProductsBySupplier(request);
        }
        
        public System.Collections.Generic.List<BA.Admin.Web.ProductWebService.ProductDto> RetrieveProductsBySupplier(int supplierId) {
            BA.Admin.Web.ProductWebService.RetrieveProductsBySupplierRequest inValue = new BA.Admin.Web.ProductWebService.RetrieveProductsBySupplierRequest();
            inValue.Body = new BA.Admin.Web.ProductWebService.RetrieveProductsBySupplierRequestBody();
            inValue.Body.supplierId = supplierId;
            BA.Admin.Web.ProductWebService.RetrieveProductsBySupplierResponse retVal = ((BA.Admin.Web.ProductWebService.ProductWebServiceSoap)(this)).RetrieveProductsBySupplier(inValue);
            return retVal.Body.RetrieveProductsBySupplierResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BA.Admin.Web.ProductWebService.RetrieveAllSupplierResponse BA.Admin.Web.ProductWebService.ProductWebServiceSoap.RetrieveAllSupplier(BA.Admin.Web.ProductWebService.RetrieveAllSupplierRequest request) {
            return base.Channel.RetrieveAllSupplier(request);
        }
        
        public System.Collections.Generic.List<BA.Admin.Web.ProductWebService.SupplierDto> RetrieveAllSupplier() {
            BA.Admin.Web.ProductWebService.RetrieveAllSupplierRequest inValue = new BA.Admin.Web.ProductWebService.RetrieveAllSupplierRequest();
            inValue.Body = new BA.Admin.Web.ProductWebService.RetrieveAllSupplierRequestBody();
            BA.Admin.Web.ProductWebService.RetrieveAllSupplierResponse retVal = ((BA.Admin.Web.ProductWebService.ProductWebServiceSoap)(this)).RetrieveAllSupplier(inValue);
            return retVal.Body.RetrieveAllSupplierResult;
        }
    }
}
