//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace BA.Web.WebPages.Contact {
    
    
    public partial class ContactMgt {
        
        /// <summary>
        /// ucIList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::BA.Web.Common.Subject.UI.InstanceList ucIList;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new BA.Web.MasterPages.AppMasterPage Master {
            get {
                return ((BA.Web.MasterPages.AppMasterPage)(base.Master));
            }
        }
    }
}
