//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.60310.0
// 
namespace BA.WebService.Silverlight.ProductWebService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductInfoDto", Namespace="http://www.orderbyapps.com/WebServices/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<BA.WebService.Silverlight.ProductWebService.ProductInfoDto>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<BA.WebService.Silverlight.ProductWebService.ReviewInfoDto>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BA.WebService.Silverlight.ProductWebService.ReviewInfoDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BA.WebService.Silverlight.ProductWebService.SupplierInfoDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<BA.WebService.Silverlight.ProductWebService.SupplierInfoDto>))]
    public partial class ProductInfoDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object ProductIdField;
        
        private string NameField;
        
        private string DescriptionField;
        
        private object CategoryIdField;
        
        private object SupplierIdField;
        
        private decimal PriceField;
        
        private byte[] SketchField;
        
        private object SellingPeriodIdField;
        
        private bool IsDiscontinuedField;
        
        private decimal DiscountAmountField;
        
        private decimal RatingField;
        
        private int NumberOfRatingsField;
        
        private string SupplierNameField;
        
        private string CategoryTextField;
        
        private string SellingPeriodNameField;
        
        private System.Nullable<System.DateTime> SellingPeriodStartTimeField;
        
        private System.Nullable<System.DateTime> SellingPeriodEndTimeField;
        
        private System.Collections.ObjectModel.ObservableCollection<BA.WebService.Silverlight.ProductWebService.ReviewInfoDto> ReviewsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductIdField, value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public object CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryIdField, value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public object SupplierId {
            get {
                return this.SupplierIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierIdField, value) != true)) {
                    this.SupplierIdField = value;
                    this.RaisePropertyChanged("SupplierId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public byte[] Sketch {
            get {
                return this.SketchField;
            }
            set {
                if ((object.ReferenceEquals(this.SketchField, value) != true)) {
                    this.SketchField = value;
                    this.RaisePropertyChanged("Sketch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public object SellingPeriodId {
            get {
                return this.SellingPeriodIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SellingPeriodIdField, value) != true)) {
                    this.SellingPeriodIdField = value;
                    this.RaisePropertyChanged("SellingPeriodId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool IsDiscontinued {
            get {
                return this.IsDiscontinuedField;
            }
            set {
                if ((this.IsDiscontinuedField.Equals(value) != true)) {
                    this.IsDiscontinuedField = value;
                    this.RaisePropertyChanged("IsDiscontinued");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public decimal DiscountAmount {
            get {
                return this.DiscountAmountField;
            }
            set {
                if ((this.DiscountAmountField.Equals(value) != true)) {
                    this.DiscountAmountField = value;
                    this.RaisePropertyChanged("DiscountAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public decimal Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((this.RatingField.Equals(value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public int NumberOfRatings {
            get {
                return this.NumberOfRatingsField;
            }
            set {
                if ((this.NumberOfRatingsField.Equals(value) != true)) {
                    this.NumberOfRatingsField = value;
                    this.RaisePropertyChanged("NumberOfRatings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string SupplierName {
            get {
                return this.SupplierNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierNameField, value) != true)) {
                    this.SupplierNameField = value;
                    this.RaisePropertyChanged("SupplierName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string CategoryText {
            get {
                return this.CategoryTextField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryTextField, value) != true)) {
                    this.CategoryTextField = value;
                    this.RaisePropertyChanged("CategoryText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string SellingPeriodName {
            get {
                return this.SellingPeriodNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SellingPeriodNameField, value) != true)) {
                    this.SellingPeriodNameField = value;
                    this.RaisePropertyChanged("SellingPeriodName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public System.Nullable<System.DateTime> SellingPeriodStartTime {
            get {
                return this.SellingPeriodStartTimeField;
            }
            set {
                if ((this.SellingPeriodStartTimeField.Equals(value) != true)) {
                    this.SellingPeriodStartTimeField = value;
                    this.RaisePropertyChanged("SellingPeriodStartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public System.Nullable<System.DateTime> SellingPeriodEndTime {
            get {
                return this.SellingPeriodEndTimeField;
            }
            set {
                if ((this.SellingPeriodEndTimeField.Equals(value) != true)) {
                    this.SellingPeriodEndTimeField = value;
                    this.RaisePropertyChanged("SellingPeriodEndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public System.Collections.ObjectModel.ObservableCollection<BA.WebService.Silverlight.ProductWebService.ReviewInfoDto> Reviews {
            get {
                return this.ReviewsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReviewsField, value) != true)) {
                    this.ReviewsField = value;
                    this.RaisePropertyChanged("Reviews");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReviewInfoDto", Namespace="http://www.orderbyapps.com/WebServices/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<BA.WebService.Silverlight.ProductWebService.ProductInfoDto>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BA.WebService.Silverlight.ProductWebService.ProductInfoDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<BA.WebService.Silverlight.ProductWebService.ReviewInfoDto>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BA.WebService.Silverlight.ProductWebService.SupplierInfoDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<BA.WebService.Silverlight.ProductWebService.SupplierInfoDto>))]
    public partial class ReviewInfoDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object ReviewIdField;
        
        private object ObjectIdField;
        
        private System.Nullable<decimal> RatingField;
        
        private string TitleField;
        
        private string ContentField;
        
        private object IssuedByIdField;
        
        private string IssuedByField;
        
        private System.DateTime IssuedTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object ReviewId {
            get {
                return this.ReviewIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ReviewIdField, value) != true)) {
                    this.ReviewIdField = value;
                    this.RaisePropertyChanged("ReviewId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public object ObjectId {
            get {
                return this.ObjectIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectIdField, value) != true)) {
                    this.ObjectIdField = value;
                    this.RaisePropertyChanged("ObjectId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<decimal> Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((this.RatingField.Equals(value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public object IssuedById {
            get {
                return this.IssuedByIdField;
            }
            set {
                if ((object.ReferenceEquals(this.IssuedByIdField, value) != true)) {
                    this.IssuedByIdField = value;
                    this.RaisePropertyChanged("IssuedById");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string IssuedBy {
            get {
                return this.IssuedByField;
            }
            set {
                if ((object.ReferenceEquals(this.IssuedByField, value) != true)) {
                    this.IssuedByField = value;
                    this.RaisePropertyChanged("IssuedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime IssuedTime {
            get {
                return this.IssuedTimeField;
            }
            set {
                if ((this.IssuedTimeField.Equals(value) != true)) {
                    this.IssuedTimeField = value;
                    this.RaisePropertyChanged("IssuedTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SupplierInfoDto", Namespace="http://www.orderbyapps.com/WebServices/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<BA.WebService.Silverlight.ProductWebService.ProductInfoDto>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BA.WebService.Silverlight.ProductWebService.ProductInfoDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<BA.WebService.Silverlight.ProductWebService.ReviewInfoDto>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(BA.WebService.Silverlight.ProductWebService.ReviewInfoDto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.ObjectModel.ObservableCollection<BA.WebService.Silverlight.ProductWebService.SupplierInfoDto>))]
    public partial class SupplierInfoDto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object SupplierIdField;
        
        private string NameField;
        
        private string AddressLine1Field;
        
        private string AddressLine2Field;
        
        private string CountryField;
        
        private string CountryStateField;
        
        private string CityField;
        
        private string ZipCodeField;
        
        private string ContactPersonField;
        
        private string ContactPhoneField;
        
        private string ContactEmailField;
        
        private string ContactFaxField;
        
        private int CategoryIdField;
        
        private int NationIdField;
        
        private string CategoryTextField;
        
        private string NationTextField;
        
        private bool AllowTakeOutField;
        
        private bool AllowReserveField;
        
        private bool AllowBringWineField;
        
        private System.Nullable<System.DateTime> DayStartTimeField;
        
        private System.Nullable<System.DateTime> DayEndTimeField;
        
        private decimal RatingField;
        
        private int NumberOfRatingsField;
        
        private byte[] LogoField;
        
        private string WebsiteField;
        
        private System.Collections.ObjectModel.ObservableCollection<BA.WebService.Silverlight.ProductWebService.ReviewInfoDto> ReviewsField;
        
        private System.Collections.ObjectModel.ObservableCollection<BA.WebService.Silverlight.ProductWebService.ProductInfoDto> ProductsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object SupplierId {
            get {
                return this.SupplierIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierIdField, value) != true)) {
                    this.SupplierIdField = value;
                    this.RaisePropertyChanged("SupplierId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AddressLine1 {
            get {
                return this.AddressLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine1Field, value) != true)) {
                    this.AddressLine1Field = value;
                    this.RaisePropertyChanged("AddressLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string AddressLine2 {
            get {
                return this.AddressLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine2Field, value) != true)) {
                    this.AddressLine2Field = value;
                    this.RaisePropertyChanged("AddressLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CountryState {
            get {
                return this.CountryStateField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryStateField, value) != true)) {
                    this.CountryStateField = value;
                    this.RaisePropertyChanged("CountryState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ContactPerson {
            get {
                return this.ContactPersonField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactPersonField, value) != true)) {
                    this.ContactPersonField = value;
                    this.RaisePropertyChanged("ContactPerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string ContactPhone {
            get {
                return this.ContactPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactPhoneField, value) != true)) {
                    this.ContactPhoneField = value;
                    this.RaisePropertyChanged("ContactPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string ContactEmail {
            get {
                return this.ContactEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactEmailField, value) != true)) {
                    this.ContactEmailField = value;
                    this.RaisePropertyChanged("ContactEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string ContactFax {
            get {
                return this.ContactFaxField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactFaxField, value) != true)) {
                    this.ContactFaxField = value;
                    this.RaisePropertyChanged("ContactFax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public int CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public int NationId {
            get {
                return this.NationIdField;
            }
            set {
                if ((this.NationIdField.Equals(value) != true)) {
                    this.NationIdField = value;
                    this.RaisePropertyChanged("NationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string CategoryText {
            get {
                return this.CategoryTextField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryTextField, value) != true)) {
                    this.CategoryTextField = value;
                    this.RaisePropertyChanged("CategoryText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string NationText {
            get {
                return this.NationTextField;
            }
            set {
                if ((object.ReferenceEquals(this.NationTextField, value) != true)) {
                    this.NationTextField = value;
                    this.RaisePropertyChanged("NationText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public bool AllowTakeOut {
            get {
                return this.AllowTakeOutField;
            }
            set {
                if ((this.AllowTakeOutField.Equals(value) != true)) {
                    this.AllowTakeOutField = value;
                    this.RaisePropertyChanged("AllowTakeOut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public bool AllowReserve {
            get {
                return this.AllowReserveField;
            }
            set {
                if ((this.AllowReserveField.Equals(value) != true)) {
                    this.AllowReserveField = value;
                    this.RaisePropertyChanged("AllowReserve");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public bool AllowBringWine {
            get {
                return this.AllowBringWineField;
            }
            set {
                if ((this.AllowBringWineField.Equals(value) != true)) {
                    this.AllowBringWineField = value;
                    this.RaisePropertyChanged("AllowBringWine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public System.Nullable<System.DateTime> DayStartTime {
            get {
                return this.DayStartTimeField;
            }
            set {
                if ((this.DayStartTimeField.Equals(value) != true)) {
                    this.DayStartTimeField = value;
                    this.RaisePropertyChanged("DayStartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public System.Nullable<System.DateTime> DayEndTime {
            get {
                return this.DayEndTimeField;
            }
            set {
                if ((this.DayEndTimeField.Equals(value) != true)) {
                    this.DayEndTimeField = value;
                    this.RaisePropertyChanged("DayEndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=21)]
        public decimal Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((this.RatingField.Equals(value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=22)]
        public int NumberOfRatings {
            get {
                return this.NumberOfRatingsField;
            }
            set {
                if ((this.NumberOfRatingsField.Equals(value) != true)) {
                    this.NumberOfRatingsField = value;
                    this.RaisePropertyChanged("NumberOfRatings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public byte[] Logo {
            get {
                return this.LogoField;
            }
            set {
                if ((object.ReferenceEquals(this.LogoField, value) != true)) {
                    this.LogoField = value;
                    this.RaisePropertyChanged("Logo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string Website {
            get {
                return this.WebsiteField;
            }
            set {
                if ((object.ReferenceEquals(this.WebsiteField, value) != true)) {
                    this.WebsiteField = value;
                    this.RaisePropertyChanged("Website");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public System.Collections.ObjectModel.ObservableCollection<BA.WebService.Silverlight.ProductWebService.ReviewInfoDto> Reviews {
            get {
                return this.ReviewsField;
            }
            set {
                if ((object.ReferenceEquals(this.ReviewsField, value) != true)) {
                    this.ReviewsField = value;
                    this.RaisePropertyChanged("Reviews");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public System.Collections.ObjectModel.ObservableCollection<BA.WebService.Silverlight.ProductWebService.ProductInfoDto> Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.orderbyapps.com/WebServices/", ConfigurationName="ProductWebService.ProductWebServiceSoap")]
    public interface ProductWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.orderbyapps.com/WebServices/RetrieveProductsBySupplier", ReplyAction="*")]
        System.IAsyncResult BeginRetrieveProductsBySupplier(BA.WebService.Silverlight.ProductWebService.RetrieveProductsBySupplierRequest request, System.AsyncCallback callback, object asyncState);
        
        BA.WebService.Silverlight.ProductWebService.RetrieveProductsBySupplierResponse EndRetrieveProductsBySupplier(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://www.orderbyapps.com/WebServices/RetrieveAllSupplier", ReplyAction="*")]
        System.IAsyncResult BeginRetrieveAllSupplier(BA.WebService.Silverlight.ProductWebService.RetrieveAllSupplierRequest request, System.AsyncCallback callback, object asyncState);
        
        BA.WebService.Silverlight.ProductWebService.RetrieveAllSupplierResponse EndRetrieveAllSupplier(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveProductsBySupplierRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveProductsBySupplier", Namespace="http://www.orderbyapps.com/WebServices/", Order=0)]
        public BA.WebService.Silverlight.ProductWebService.RetrieveProductsBySupplierRequestBody Body;
        
        public RetrieveProductsBySupplierRequest() {
        }
        
        public RetrieveProductsBySupplierRequest(BA.WebService.Silverlight.ProductWebService.RetrieveProductsBySupplierRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.orderbyapps.com/WebServices/")]
    public partial class RetrieveProductsBySupplierRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int supplierId;
        
        public RetrieveProductsBySupplierRequestBody() {
        }
        
        public RetrieveProductsBySupplierRequestBody(int supplierId) {
            this.supplierId = supplierId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveProductsBySupplierResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveProductsBySupplierResponse", Namespace="http://www.orderbyapps.com/WebServices/", Order=0)]
        public BA.WebService.Silverlight.ProductWebService.RetrieveProductsBySupplierResponseBody Body;
        
        public RetrieveProductsBySupplierResponse() {
        }
        
        public RetrieveProductsBySupplierResponse(BA.WebService.Silverlight.ProductWebService.RetrieveProductsBySupplierResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.orderbyapps.com/WebServices/")]
    public partial class RetrieveProductsBySupplierResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<BA.WebService.Silverlight.ProductWebService.ProductInfoDto> RetrieveProductsBySupplierResult;
        
        public RetrieveProductsBySupplierResponseBody() {
        }
        
        public RetrieveProductsBySupplierResponseBody(System.Collections.ObjectModel.ObservableCollection<BA.WebService.Silverlight.ProductWebService.ProductInfoDto> RetrieveProductsBySupplierResult) {
            this.RetrieveProductsBySupplierResult = RetrieveProductsBySupplierResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveAllSupplierRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveAllSupplier", Namespace="http://www.orderbyapps.com/WebServices/", Order=0)]
        public BA.WebService.Silverlight.ProductWebService.RetrieveAllSupplierRequestBody Body;
        
        public RetrieveAllSupplierRequest() {
        }
        
        public RetrieveAllSupplierRequest(BA.WebService.Silverlight.ProductWebService.RetrieveAllSupplierRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RetrieveAllSupplierRequestBody {
        
        public RetrieveAllSupplierRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveAllSupplierResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveAllSupplierResponse", Namespace="http://www.orderbyapps.com/WebServices/", Order=0)]
        public BA.WebService.Silverlight.ProductWebService.RetrieveAllSupplierResponseBody Body;
        
        public RetrieveAllSupplierResponse() {
        }
        
        public RetrieveAllSupplierResponse(BA.WebService.Silverlight.ProductWebService.RetrieveAllSupplierResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.orderbyapps.com/WebServices/")]
    public partial class RetrieveAllSupplierResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.ObjectModel.ObservableCollection<BA.WebService.Silverlight.ProductWebService.SupplierInfoDto> RetrieveAllSupplierResult;
        
        public RetrieveAllSupplierResponseBody() {
        }
        
        public RetrieveAllSupplierResponseBody(System.Collections.ObjectModel.ObservableCollection<BA.WebService.Silverlight.ProductWebService.SupplierInfoDto> RetrieveAllSupplierResult) {
            this.RetrieveAllSupplierResult = RetrieveAllSupplierResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductWebServiceSoapChannel : BA.WebService.Silverlight.ProductWebService.ProductWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetrieveProductsBySupplierCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RetrieveProductsBySupplierCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<BA.WebService.Silverlight.ProductWebService.ProductInfoDto> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<BA.WebService.Silverlight.ProductWebService.ProductInfoDto>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetrieveAllSupplierCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RetrieveAllSupplierCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<BA.WebService.Silverlight.ProductWebService.SupplierInfoDto> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<BA.WebService.Silverlight.ProductWebService.SupplierInfoDto>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductWebServiceSoapClient : System.ServiceModel.ClientBase<BA.WebService.Silverlight.ProductWebService.ProductWebServiceSoap>, BA.WebService.Silverlight.ProductWebService.ProductWebServiceSoap {
        
        private BeginOperationDelegate onBeginRetrieveProductsBySupplierDelegate;
        
        private EndOperationDelegate onEndRetrieveProductsBySupplierDelegate;
        
        private System.Threading.SendOrPostCallback onRetrieveProductsBySupplierCompletedDelegate;
        
        private BeginOperationDelegate onBeginRetrieveAllSupplierDelegate;
        
        private EndOperationDelegate onEndRetrieveAllSupplierDelegate;
        
        private System.Threading.SendOrPostCallback onRetrieveAllSupplierCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ProductWebServiceSoapClient() {
        }
        
        public ProductWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<RetrieveProductsBySupplierCompletedEventArgs> RetrieveProductsBySupplierCompleted;
        
        public event System.EventHandler<RetrieveAllSupplierCompletedEventArgs> RetrieveAllSupplierCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult BA.WebService.Silverlight.ProductWebService.ProductWebServiceSoap.BeginRetrieveProductsBySupplier(BA.WebService.Silverlight.ProductWebService.RetrieveProductsBySupplierRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRetrieveProductsBySupplier(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginRetrieveProductsBySupplier(int supplierId, System.AsyncCallback callback, object asyncState) {
            BA.WebService.Silverlight.ProductWebService.RetrieveProductsBySupplierRequest inValue = new BA.WebService.Silverlight.ProductWebService.RetrieveProductsBySupplierRequest();
            inValue.Body = new BA.WebService.Silverlight.ProductWebService.RetrieveProductsBySupplierRequestBody();
            inValue.Body.supplierId = supplierId;
            return ((BA.WebService.Silverlight.ProductWebService.ProductWebServiceSoap)(this)).BeginRetrieveProductsBySupplier(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BA.WebService.Silverlight.ProductWebService.RetrieveProductsBySupplierResponse BA.WebService.Silverlight.ProductWebService.ProductWebServiceSoap.EndRetrieveProductsBySupplier(System.IAsyncResult result) {
            return base.Channel.EndRetrieveProductsBySupplier(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.Collections.ObjectModel.ObservableCollection<BA.WebService.Silverlight.ProductWebService.ProductInfoDto> EndRetrieveProductsBySupplier(System.IAsyncResult result) {
            BA.WebService.Silverlight.ProductWebService.RetrieveProductsBySupplierResponse retVal = ((BA.WebService.Silverlight.ProductWebService.ProductWebServiceSoap)(this)).EndRetrieveProductsBySupplier(result);
            return retVal.Body.RetrieveProductsBySupplierResult;
        }
        
        private System.IAsyncResult OnBeginRetrieveProductsBySupplier(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int supplierId = ((int)(inValues[0]));
            return this.BeginRetrieveProductsBySupplier(supplierId, callback, asyncState);
        }
        
        private object[] OnEndRetrieveProductsBySupplier(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<BA.WebService.Silverlight.ProductWebService.ProductInfoDto> retVal = this.EndRetrieveProductsBySupplier(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRetrieveProductsBySupplierCompleted(object state) {
            if ((this.RetrieveProductsBySupplierCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RetrieveProductsBySupplierCompleted(this, new RetrieveProductsBySupplierCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RetrieveProductsBySupplierAsync(int supplierId) {
            this.RetrieveProductsBySupplierAsync(supplierId, null);
        }
        
        public void RetrieveProductsBySupplierAsync(int supplierId, object userState) {
            if ((this.onBeginRetrieveProductsBySupplierDelegate == null)) {
                this.onBeginRetrieveProductsBySupplierDelegate = new BeginOperationDelegate(this.OnBeginRetrieveProductsBySupplier);
            }
            if ((this.onEndRetrieveProductsBySupplierDelegate == null)) {
                this.onEndRetrieveProductsBySupplierDelegate = new EndOperationDelegate(this.OnEndRetrieveProductsBySupplier);
            }
            if ((this.onRetrieveProductsBySupplierCompletedDelegate == null)) {
                this.onRetrieveProductsBySupplierCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRetrieveProductsBySupplierCompleted);
            }
            base.InvokeAsync(this.onBeginRetrieveProductsBySupplierDelegate, new object[] {
                        supplierId}, this.onEndRetrieveProductsBySupplierDelegate, this.onRetrieveProductsBySupplierCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult BA.WebService.Silverlight.ProductWebService.ProductWebServiceSoap.BeginRetrieveAllSupplier(BA.WebService.Silverlight.ProductWebService.RetrieveAllSupplierRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRetrieveAllSupplier(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginRetrieveAllSupplier(System.AsyncCallback callback, object asyncState) {
            BA.WebService.Silverlight.ProductWebService.RetrieveAllSupplierRequest inValue = new BA.WebService.Silverlight.ProductWebService.RetrieveAllSupplierRequest();
            inValue.Body = new BA.WebService.Silverlight.ProductWebService.RetrieveAllSupplierRequestBody();
            return ((BA.WebService.Silverlight.ProductWebService.ProductWebServiceSoap)(this)).BeginRetrieveAllSupplier(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BA.WebService.Silverlight.ProductWebService.RetrieveAllSupplierResponse BA.WebService.Silverlight.ProductWebService.ProductWebServiceSoap.EndRetrieveAllSupplier(System.IAsyncResult result) {
            return base.Channel.EndRetrieveAllSupplier(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.Collections.ObjectModel.ObservableCollection<BA.WebService.Silverlight.ProductWebService.SupplierInfoDto> EndRetrieveAllSupplier(System.IAsyncResult result) {
            BA.WebService.Silverlight.ProductWebService.RetrieveAllSupplierResponse retVal = ((BA.WebService.Silverlight.ProductWebService.ProductWebServiceSoap)(this)).EndRetrieveAllSupplier(result);
            return retVal.Body.RetrieveAllSupplierResult;
        }
        
        private System.IAsyncResult OnBeginRetrieveAllSupplier(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginRetrieveAllSupplier(callback, asyncState);
        }
        
        private object[] OnEndRetrieveAllSupplier(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<BA.WebService.Silverlight.ProductWebService.SupplierInfoDto> retVal = this.EndRetrieveAllSupplier(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRetrieveAllSupplierCompleted(object state) {
            if ((this.RetrieveAllSupplierCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RetrieveAllSupplierCompleted(this, new RetrieveAllSupplierCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RetrieveAllSupplierAsync() {
            this.RetrieveAllSupplierAsync(null);
        }
        
        public void RetrieveAllSupplierAsync(object userState) {
            if ((this.onBeginRetrieveAllSupplierDelegate == null)) {
                this.onBeginRetrieveAllSupplierDelegate = new BeginOperationDelegate(this.OnBeginRetrieveAllSupplier);
            }
            if ((this.onEndRetrieveAllSupplierDelegate == null)) {
                this.onEndRetrieveAllSupplierDelegate = new EndOperationDelegate(this.OnEndRetrieveAllSupplier);
            }
            if ((this.onRetrieveAllSupplierCompletedDelegate == null)) {
                this.onRetrieveAllSupplierCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRetrieveAllSupplierCompleted);
            }
            base.InvokeAsync(this.onBeginRetrieveAllSupplierDelegate, null, this.onEndRetrieveAllSupplierDelegate, this.onRetrieveAllSupplierCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override BA.WebService.Silverlight.ProductWebService.ProductWebServiceSoap CreateChannel() {
            return new ProductWebServiceSoapClientChannel(this);
        }
        
        private class ProductWebServiceSoapClientChannel : ChannelBase<BA.WebService.Silverlight.ProductWebService.ProductWebServiceSoap>, BA.WebService.Silverlight.ProductWebService.ProductWebServiceSoap {
            
            public ProductWebServiceSoapClientChannel(System.ServiceModel.ClientBase<BA.WebService.Silverlight.ProductWebService.ProductWebServiceSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginRetrieveProductsBySupplier(BA.WebService.Silverlight.ProductWebService.RetrieveProductsBySupplierRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("RetrieveProductsBySupplier", _args, callback, asyncState);
                return _result;
            }
            
            public BA.WebService.Silverlight.ProductWebService.RetrieveProductsBySupplierResponse EndRetrieveProductsBySupplier(System.IAsyncResult result) {
                object[] _args = new object[0];
                BA.WebService.Silverlight.ProductWebService.RetrieveProductsBySupplierResponse _result = ((BA.WebService.Silverlight.ProductWebService.RetrieveProductsBySupplierResponse)(base.EndInvoke("RetrieveProductsBySupplier", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRetrieveAllSupplier(BA.WebService.Silverlight.ProductWebService.RetrieveAllSupplierRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("RetrieveAllSupplier", _args, callback, asyncState);
                return _result;
            }
            
            public BA.WebService.Silverlight.ProductWebService.RetrieveAllSupplierResponse EndRetrieveAllSupplier(System.IAsyncResult result) {
                object[] _args = new object[0];
                BA.WebService.Silverlight.ProductWebService.RetrieveAllSupplierResponse _result = ((BA.WebService.Silverlight.ProductWebService.RetrieveAllSupplierResponse)(base.EndInvoke("RetrieveAllSupplier", _args, result)));
                return _result;
            }
        }
    }
}
