//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SiteMapLocalizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SiteMapLocalizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SiteMapLocalizations", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Edit.
        /// </summary>
        internal static string ActivityEditTitle {
            get {
                return ResourceManager.GetString("ActivityEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Manager.
        /// </summary>
        internal static string ActivityManagerTitle {
            get {
                return ResourceManager.GetString("ActivityManagerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Management.
        /// </summary>
        internal static string ActivitysManagementTitle {
            get {
                return ResourceManager.GetString("ActivitysManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        internal static string AdministrationTitle {
            get {
                return ResourceManager.GetString("AdministrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        internal static string ApplicationSettingsTitle {
            get {
                return ResourceManager.GetString("ApplicationSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog Manager.
        /// </summary>
        internal static string CatalogManagerTitle {
            get {
                return ResourceManager.GetString("CatalogManagerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalogs Management.
        /// </summary>
        internal static string CatalogsManagementTitle {
            get {
                return ResourceManager.GetString("CatalogsManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Management.
        /// </summary>
        internal static string CategoryManagementTitle {
            get {
                return ResourceManager.GetString("CategoryManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Manager.
        /// </summary>
        internal static string CategoryManagerTitle {
            get {
                return ResourceManager.GetString("CategoryManagerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        internal static string CheckoutTitle {
            get {
                return ResourceManager.GetString("CheckoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Edit.
        /// </summary>
        internal static string ContactEditTitle {
            get {
                return ResourceManager.GetString("ContactEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Import.
        /// </summary>
        internal static string ContactImportTitle {
            get {
                return ResourceManager.GetString("ContactImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Manager.
        /// </summary>
        internal static string ContactManagerTitle {
            get {
                return ResourceManager.GetString("ContactManagerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts Management.
        /// </summary>
        internal static string ContactsManagementTitle {
            get {
                return ResourceManager.GetString("ContactsManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string ContactUsPageTitle {
            get {
                return ResourceManager.GetString("ContactUsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Edit.
        /// </summary>
        internal static string CustomerEditTitle {
            get {
                return ResourceManager.GetString("CustomerEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Manager.
        /// </summary>
        internal static string CustomerManagerTitle {
            get {
                return ResourceManager.GetString("CustomerManagerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers Management.
        /// </summary>
        internal static string CustomersManagementTitle {
            get {
                return ResourceManager.GetString("CustomersManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string DashboardTitle {
            get {
                return ResourceManager.GetString("DashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Edit.
        /// </summary>
        internal static string DocumentEditTitle {
            get {
                return ResourceManager.GetString("DocumentEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Manager.
        /// </summary>
        internal static string DocumentManagerTitle {
            get {
                return ResourceManager.GetString("DocumentManagerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents Management.
        /// </summary>
        internal static string DocumentsManagementTitle {
            get {
                return ResourceManager.GetString("DocumentsManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Management.
        /// </summary>
        internal static string DomainManagementTitle {
            get {
                return ResourceManager.GetString("DomainManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Manager.
        /// </summary>
        internal static string DomainManagerTitle {
            get {
                return ResourceManager.GetString("DomainManagerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Edit.
        /// </summary>
        internal static string EmployeeEditTitle {
            get {
                return ResourceManager.GetString("EmployeeEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Manager.
        /// </summary>
        internal static string EmployeeManagerTitle {
            get {
                return ResourceManager.GetString("EmployeeManagerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees Management.
        /// </summary>
        internal static string EmployeesManagementTitle {
            get {
                return ResourceManager.GetString("EmployeesManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Edit.
        /// </summary>
        internal static string EntityEditTitle {
            get {
                return ResourceManager.GetString("EntityEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Management.
        /// </summary>
        internal static string EntityManagementTitle {
            get {
                return ResourceManager.GetString("EntityManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Manager.
        /// </summary>
        internal static string EntityManagerTitle {
            get {
                return ResourceManager.GetString("EntityManagerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum.
        /// </summary>
        internal static string ForumTitle {
            get {
                return ResourceManager.GetString("ForumTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic Edit.
        /// </summary>
        internal static string ForumTopicEditTitle {
            get {
                return ResourceManager.GetString("ForumTopicEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic Management.
        /// </summary>
        internal static string ForumTopicManagementTitle {
            get {
                return ResourceManager.GetString("ForumTopicManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic Manager.
        /// </summary>
        internal static string ForumTopicManagerTitle {
            get {
                return ResourceManager.GetString("ForumTopicManagerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string GlobalProductExplorerTitle {
            get {
                return ResourceManager.GetString("GlobalProductExplorerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Center.
        /// </summary>
        internal static string HelpCenterTitle {
            get {
                return ResourceManager.GetString("HelpCenterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MainMenu Management.
        /// </summary>
        internal static string MainMenuManagementTitle {
            get {
                return ResourceManager.GetString("MainMenuManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Detail.
        /// </summary>
        internal static string MonoProductDetailTitle {
            get {
                return ResourceManager.GetString("MonoProductDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MultiLanguage Setup.
        /// </summary>
        internal static string MultiLanguageSetupTitle {
            get {
                return ResourceManager.GetString("MultiLanguageSetupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Detail.
        /// </summary>
        internal static string NewsDetailTitle {
            get {
                return ResourceManager.GetString("NewsDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Edit.
        /// </summary>
        internal static string NewsEditTitle {
            get {
                return ResourceManager.GetString("NewsEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Management.
        /// </summary>
        internal static string NewsManagementTitle {
            get {
                return ResourceManager.GetString("NewsManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Manager.
        /// </summary>
        internal static string NewsManagerTitle {
            get {
                return ResourceManager.GetString("NewsManagerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        internal static string NewsTitle {
            get {
                return ResourceManager.GetString("NewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Edit.
        /// </summary>
        internal static string OrderEditTitle {
            get {
                return ResourceManager.GetString("OrderEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Manager.
        /// </summary>
        internal static string OrderManagerTitle {
            get {
                return ResourceManager.GetString("OrderManagerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Process.
        /// </summary>
        internal static string OrderProcessTitle {
            get {
                return ResourceManager.GetString("OrderProcessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Query.
        /// </summary>
        internal static string OrderQueryTitle {
            get {
                return ResourceManager.GetString("OrderQueryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders Management.
        /// </summary>
        internal static string OrdersManagementTitle {
            get {
                return ResourceManager.GetString("OrdersManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Tracking.
        /// </summary>
        internal static string OrderTrackingTitle {
            get {
                return ResourceManager.GetString("OrderTrackingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        internal static string PersonalInformationTitle {
            get {
                return ResourceManager.GetString("PersonalInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Detail.
        /// </summary>
        internal static string ProductDetailTitle {
            get {
                return ResourceManager.GetString("ProductDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Edit.
        /// </summary>
        internal static string ProductEditTitle {
            get {
                return ResourceManager.GetString("ProductEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Explorer.
        /// </summary>
        internal static string ProductExplorerTitle {
            get {
                return ResourceManager.GetString("ProductExplorerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Import.
        /// </summary>
        internal static string ProductImportTitle {
            get {
                return ResourceManager.GetString("ProductImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Manager.
        /// </summary>
        internal static string ProductManagerTitle {
            get {
                return ResourceManager.GetString("ProductManagerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products Management.
        /// </summary>
        internal static string ProductsManagementTitle {
            get {
                return ResourceManager.GetString("ProductsManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote Request.
        /// </summary>
        internal static string QuoteCreationWizardTitle {
            get {
                return ResourceManager.GetString("QuoteCreationWizardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SellingPeriods Management.
        /// </summary>
        internal static string SellingPeriodsManagementTitle {
            get {
                return ResourceManager.GetString("SellingPeriodsManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetupMenu Management.
        /// </summary>
        internal static string SetupMenuManagementTitle {
            get {
                return ResourceManager.GetString("SetupMenuManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipTo Edit.
        /// </summary>
        internal static string ShipToEditTitle {
            get {
                return ResourceManager.GetString("ShipToEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipTo Manager.
        /// </summary>
        internal static string ShipToManagerTitle {
            get {
                return ResourceManager.GetString("ShipToManagerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShipTos Management.
        /// </summary>
        internal static string ShipTosManagementTitle {
            get {
                return ResourceManager.GetString("ShipTosManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shop Around.
        /// </summary>
        internal static string ShopAroundTitle {
            get {
                return ResourceManager.GetString("ShopAroundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping Cart.
        /// </summary>
        internal static string ShoppingCartTitle {
            get {
                return ResourceManager.GetString("ShoppingCartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignIn.
        /// </summary>
        internal static string SignInTitle {
            get {
                return ResourceManager.GetString("SignInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMTP test.
        /// </summary>
        internal static string SMTPtestTitle {
            get {
                return ResourceManager.GetString("SMTPtestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject Management.
        /// </summary>
        internal static string SubjectManagementTitle {
            get {
                return ResourceManager.GetString("SubjectManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject Manager.
        /// </summary>
        internal static string SubjectManagerTitle {
            get {
                return ResourceManager.GetString("SubjectManagerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Detail.
        /// </summary>
        internal static string SupplierDetailTitle {
            get {
                return ResourceManager.GetString("SupplierDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Edit.
        /// </summary>
        internal static string SupplierEditTitle {
            get {
                return ResourceManager.GetString("SupplierEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Explorer.
        /// </summary>
        internal static string SupplierExplorerTitle {
            get {
                return ResourceManager.GetString("SupplierExplorerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Import.
        /// </summary>
        internal static string SupplierImportTitle {
            get {
                return ResourceManager.GetString("SupplierImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Manager.
        /// </summary>
        internal static string SupplierManagerTitle {
            get {
                return ResourceManager.GetString("SupplierManagerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Detail.
        /// </summary>
        internal static string SupplierProductDetailTitle {
            get {
                return ResourceManager.GetString("SupplierProductDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Product Import.
        /// </summary>
        internal static string SupplierProductImportTitle {
            get {
                return ResourceManager.GetString("SupplierProductImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers Management.
        /// </summary>
        internal static string SuppliersManagementTitle {
            get {
                return ResourceManager.GetString("SuppliersManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic Detail.
        /// </summary>
        internal static string TopicDetailTitle {
            get {
                return ResourceManager.GetString("TopicDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Edit.
        /// </summary>
        internal static string TransactionEditTitle {
            get {
                return ResourceManager.GetString("TransactionEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Manager.
        /// </summary>
        internal static string TransactionManagerTitle {
            get {
                return ResourceManager.GetString("TransactionManagerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions Management.
        /// </summary>
        internal static string TransactionsManagementTitle {
            get {
                return ResourceManager.GetString("TransactionsManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Edit.
        /// </summary>
        internal static string UserEditTitle {
            get {
                return ResourceManager.GetString("UserEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Management.
        /// </summary>
        internal static string UserManagementTitle {
            get {
                return ResourceManager.GetString("UserManagementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Manager.
        /// </summary>
        internal static string UserManagerTitle {
            get {
                return ResourceManager.GetString("UserManagerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning Page.
        /// </summary>
        internal static string WarningPageTitle {
            get {
                return ResourceManager.GetString("WarningPageTitle", resourceCulture);
            }
        }
    }
}
